export const UI_TEXT = Object.freeze({
  badge: "image-upload",
  summaryLoading: "上传卡片生成中",
  summarySuccess: "上传卡片已就绪",
  summaryError: "上传卡片生成失败",
  loadingTitle: "上传卡片生成中...",
  loadingRuntimeDetail: "正在整理多槽位上传配置...",
  loadingStreamingDetail: "正在等待 AI 输出完整的上传配置",
  errorTitle: "无法渲染该上传卡片。",
  actionInsert: "插入到聊天框",
  actionSubmit: "上传完成并继续",
  actionSubmitting: "继续中...",
  actionCompleted: "已完成",
  statusPending: "未上传",
  statusReady: "待上传",
  statusUploading: "上传中",
  statusUploaded: "已上传",
  statusFailed: "失败",
  statusReplaceable: "可替换",
  hintPending: "请先选择必填图片。",
  hintReady: "已选择必填图片，点击“上传完成并继续”后发送。",
  hintUploaded: "必填图片已上传，可继续插入或发送。",
  hintSubmitting: "正在上传素材并继续，请稍候。",
  hintCompleted: "已上传并继续，本卡片已锁定。",
  uploadLabel: "选择图片",
  previewLabel: "点击可替换",
  actionUploadFirst: "请先点击“上传完成并继续”后再继续",
  dropHint: "支持 png / jpeg / webp",
});
