export const UI_TEXT = Object.freeze({
  badge: "文件",
  summaryLoading: "文件卡片生成中",
  summarySuccessUrl: "下载链接已就绪",
  summarySuccessPath: "工作区文件已识别",
  summaryError: "文件卡片生成失败",
  loadingTitle: "文件卡片生成中...",
  loadingRuntimeDetail: "正在整理文件链接与路径信息...",
  loadingStreamingDetail: "正在等待 AI 输出完整的文件信息",
  errorTitle: "无法渲染该文件卡片。",
  kindUrl: "下载链接",
  kindPath: "工作区文件",
  metaUrl: "来源",
  metaPath: "存放",
  actionDownload: "下载",
  actionCopyLink: "复制链接",
  actionCopyPath: "复制路径",
  actionCopied: "已复制",
});
