export const UI_TEXT = Object.freeze({
  badge: "图表",
  actionInsert: "发送至聊天框",
  actionAsk: "询问该图表",
  toggleShowSource: "显示源码",
  toggleHideSource: "隐藏源码",
  summaryLoading: "图表生成中",
  summarySuccess: "图表预览已生成",
  summaryError: "图表预览失败",
  loadingTitle: "图表生成中...",
  loadingRuntimeDetail: "正在加载本地图表运行时...",
  loadingStreamingDetail: "正在等待 AI 输出完整的图表配置",
  errorTitle: "无法渲染该图表。",
  detailTitle: "图表元素详情",
  detailClose: "关闭",
  detailActionAsk: "询问该元素",
  detailActionInsert: "发送至聊天框",
  detailSeries: "系列",
  detailName: "名称",
  detailValue: "值",
  detailComponent: "组件",
  detailSeriesType: "系列类型",
  detailDataType: "数据类型",
  detailDataIndex: "数据索引",
  detailColor: "颜色",
  detailRawData: "原始数据",
  detailRawParams: "事件参数",
  detailNoData: "当前元素没有可展示的详情。",
  detailPromptLead: "请根据下面这个图表元素继续说明，并结合上下文分析。",
  detailPromptData: "数据项",
  promptLead: "请根据下面的图表摘要继续说明。",
  promptTitle: "图表标题",
  promptSubtitle: "图表副标题",
  promptTypes: "图表类型",
  promptLegend: "图例",
  promptAxes: "坐标轴",
  promptSeries: "系列概览",
});
