#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TOOL_DIR="$ROOT_DIR/tools/openclaw-control-ui-echarts"
OUTPUT_DIR="$TOOL_DIR/generated/control-ui"
CONTROL_UI_RUNTIME_SCRIPT="$TOOL_DIR/openclaw-echarts-renderer.js"
CONTROL_UI_RUNTIME_MODULE_DIR="$TOOL_DIR/runtime"
CONTROL_UI_STATIC_DIR="$TOOL_DIR/static"
OFFLINE_BUNDLED_USERSCRIPT="$ROOT_DIR/tools/openclaw-echarts-userscript/openclaw-echarts-renderer.user.js"
OVERRIDE_PATH="$ROOT_DIR/docker-compose.override.yml"
ENV_FILE="$ROOT_DIR/.env"

GENERATED_MARKER="# Generated by tools/openclaw-control-ui-echarts setup tool"
LEGACY_GENERATED_MARKER="# Generated by tools/openclaw-control-ui-echarts/setup-direct-docker-compose-up.mjs"

tmp_dir="$(mktemp -d)"
container_id=""

cleanup() {
  if [[ -n "$container_id" ]]; then
    docker rm -f "$container_id" >/dev/null 2>&1 || true
  fi
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

COLLECTED_EXTRA_MOUNTS=()

fail() {
  printf '%s\n' "ERROR: $*" >&2
  exit 1
}

require_file() {
  local file_path="$1"
  local label="$2"
  [[ -f "$file_path" ]] || fail "$label not found at $file_path"
}

require_dir() {
  local dir_path="$1"
  local label="$2"
  [[ -d "$dir_path" ]] || fail "$label not found at $dir_path"
}

trim_whitespace() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s\n' "$value"
}

read_dotenv_value() {
  local key="$1"
  [[ -f "$ENV_FILE" ]] || return 0

  awk -F= -v key="$key" '
    index($0, key "=") == 1 {
      sub(/^[^=]*=/, "")
      sub(/\r$/, "")
      print
      exit
    }
  ' "$ENV_FILE"
}

resolve_auto_gateway_token() {
  local token="${OPENCLAW_GATEWAY_TOKEN:-}"
  if [[ -z "$token" ]]; then
    token="$(read_dotenv_value OPENCLAW_GATEWAY_TOKEN || true)"
  fi
  trim_whitespace "$token"
}

inject_lufeng_public_bootstrap() {
  local index_path="$1"
  local token="$2"
  local python_bin

  python_bin="$(resolve_python)"

  "$python_bin" - "$index_path" "$token" <<'PY'
import json
import pathlib
import sys

index_path = pathlib.Path(sys.argv[1])
token = (sys.argv[2] or "").strip()

html = index_path.read_text(encoding="utf-8")
if "data-openclaw-lufeng-bootstrap" in html:
    raise SystemExit(0)

agent_id = "subotech-finance"
session_key = f"agent:{agent_id}:main"
route = "/lufeng"
route_chat = "/lufeng/chat"

token_literal = (
    json.dumps(token)
    .replace("<", "\\u003c")
    .replace(">", "\\u003e")
    .replace("&", "\\u0026")
    .replace("\u2028", "\\u2028")
    .replace("\u2029", "\\u2029")
)

script = f"""    <script data-openclaw-lufeng-bootstrap>
      ((rawToken) => {{
        const ROUTE = {json.dumps(route)};
        const CHAT_ROUTE = {json.dumps(route_chat)};
        const SESSION_KEY = {json.dumps(session_key)};
        const normalizePath = (value) => {{
          const raw = String(value ?? "").trim() || "/";
          const prefixed = raw.startsWith("/") ? raw : `/${{raw}}`;
          if (prefixed.length > 1 && prefixed.endsWith("/")) {{
            return prefixed.slice(0, -1);
          }}
          return prefixed;
        }};
        const isLufengPath = (pathname) => {{
          const normalized = normalizePath(pathname);
          return normalized === ROUTE || normalized === CHAT_ROUTE;
        }};
        if (
          typeof window === "undefined" ||
          typeof document === "undefined" ||
          typeof location === "undefined" ||
          !isLufengPath(location.pathname)
        ) {{
          return;
        }}
        const normalizeGatewayScope = (gatewayUrl) => {{
          const trimmed = String(gatewayUrl ?? "").trim();
          if (!trimmed) {{
            return "default";
          }}
          try {{
            const parsed = new URL(
              trimmed,
              `${{window.location.protocol}}//${{window.location.host}}/`,
            );
            const pathname =
              parsed.pathname === "/"
                ? ""
                : parsed.pathname.replace(/\\/+$/, "") || parsed.pathname;
            return `${{parsed.protocol}}//${{parsed.host}}${{pathname}}`;
          }} catch {{
            return trimmed;
          }}
        }};
        const buildSettingsStorageKey = (gatewayUrl) =>
          `openclaw.control.settings.v1:${{normalizeGatewayScope(gatewayUrl)}}`;
        const buildTokenStorageKey = (gatewayUrl) =>
          `openclaw.control.token.v1:${{normalizeGatewayScope(gatewayUrl)}}`;
        const normalizeLufengRouteUrl = (urlLike, baseHref = window.location.href) => {{
          const url = new URL(urlLike, baseHref);
          if (!isLufengPath(url.pathname)) {{
            return url;
          }}
          const normalized = normalizePath(url.pathname);
          if (normalized === CHAT_ROUTE) {{
            url.pathname = ROUTE;
          }}
          if (normalizePath(url.pathname) === ROUTE) {{
            url.searchParams.delete("session");
          }}
          return url;
        }};

        const gatewayOrigin = `${{location.protocol === "https:" ? "wss:" : "ws:"}}//${{location.host}}`;
        const lufengScopeUrl = `${{gatewayOrigin}}${{ROUTE}}`;
        const rootGatewayScope = normalizeGatewayScope(gatewayOrigin);

        window.__OPENCLAW_CONTROL_UI_BASE_PATH__ = ROUTE;
        window.__OPENCLAW_LUFENG_MODE__ = true;
        document.documentElement.setAttribute("data-oc-lufeng-route", "true");

        try {{
          const storage = window.localStorage;
          if (storage) {{
            const key = buildSettingsStorageKey(lufengScopeUrl);
            const existingRaw = storage.getItem(key);
            const existing =
              existingRaw && existingRaw.trim()
                ? JSON.parse(existingRaw)
                : {{}};
            const next = {{
              ...existing,
              gatewayUrl: gatewayOrigin,
              sessionKey: SESSION_KEY,
              lastActiveSessionKey: SESSION_KEY,
              sessionsByGateway: {{
                ...(existing.sessionsByGateway && typeof existing.sessionsByGateway === "object"
                  ? existing.sessionsByGateway
                  : {{}}),
                [rootGatewayScope]: {{
                  sessionKey: SESSION_KEY,
                  lastActiveSessionKey: SESSION_KEY,
                }},
              }},
            }};
            storage.setItem(key, JSON.stringify(next));
          }}
        }} catch {{
          // best-effort only
        }}

        try {{
          const normalizedToken = String(rawToken ?? "").trim();
          if (normalizedToken && window.sessionStorage) {{
            window.sessionStorage.setItem(
              buildTokenStorageKey(gatewayOrigin),
              normalizedToken,
            );
          }}
        }} catch {{
          // best-effort only
        }}

        if (!window.__OPENCLAW_LUFENG_HISTORY_PATCHED__) {{
          const originalReplaceState = window.history.replaceState.bind(window.history);
          const originalPushState = window.history.pushState.bind(window.history);
          const wrap =
            (original) =>
            (state, unused, url) => {{
              if (url == null) {{
                return original(state, unused, url);
              }}
              const normalized = normalizeLufengRouteUrl(url, window.location.href);
              return original(state, unused, normalized.toString());
            }};
          window.history.replaceState = wrap(originalReplaceState);
          window.history.pushState = wrap(originalPushState);
          window.__OPENCLAW_LUFENG_HISTORY_PATCHED__ = true;
        }}

        const normalizedCurrent = normalizeLufengRouteUrl(window.location.href, window.location.href);
        if (
          normalizedCurrent.pathname !== window.location.pathname ||
          normalizedCurrent.search !== window.location.search
        ) {{
          window.history.replaceState({{}}, "", normalizedCurrent.toString());
        }}
      }})({token_literal});
    </script>
"""

if "</head>" not in html:
    raise SystemExit(f"index.html is missing </head>: {index_path}")

html = html.replace("  </head>", f"{script}\n  </head>", 1)
index_path.write_text(html, encoding="utf-8")
PY
}

validate_extra_mount_spec() {
  local mount="$1"

  [[ "$mount" == *$'\n'* || "$mount" == *$'\r'* || "$mount" == *$'\t'* ]] && \
    fail "OPENCLAW_EXTRA_MOUNTS entries cannot contain control characters."

  [[ "$mount" =~ [[:space:]] ]] && \
    fail "OPENCLAW_EXTRA_MOUNTS entries must not contain spaces."

  [[ "$mount" == *:* ]] || fail "Invalid OPENCLAW_EXTRA_MOUNTS entry: $mount"
}

collect_extra_mounts() {
  local raw_mounts="${OPENCLAW_EXTRA_MOUNTS:-}"
  local mount=""

  COLLECTED_EXTRA_MOUNTS=()

  if [[ -z "$raw_mounts" ]]; then
    raw_mounts="$(read_dotenv_value OPENCLAW_EXTRA_MOUNTS || true)"
  fi

  raw_mounts="$(trim_whitespace "$raw_mounts")"
  [[ -n "$raw_mounts" ]] || return 0

  [[ "$raw_mounts" == *$'\n'* || "$raw_mounts" == *$'\r'* || "$raw_mounts" == *$'\t'* ]] && \
    fail "OPENCLAW_EXTRA_MOUNTS cannot contain control characters."

  IFS=',' read -r -a mounts <<<"$raw_mounts"
  for mount in "${mounts[@]}"; do
    mount="$(trim_whitespace "$mount")"
    [[ -n "$mount" ]] || continue
    validate_extra_mount_spec "$mount"
    COLLECTED_EXTRA_MOUNTS+=("$mount")
  done
}

resolve_python() {
  if command -v python3 >/dev/null 2>&1; then
    printf '%s\n' "python3"
    return 0
  fi

  if command -v python >/dev/null 2>&1; then
    printf '%s\n' "python"
    return 0
  fi

  fail "python3 or python is required to extract the bundled vendor libraries."
}

resolve_gateway_image_ref() {
  if [[ -n "${OPENCLAW_IMAGE:-}" ]]; then
    printf '%s\n' "$OPENCLAW_IMAGE"
    return 0
  fi

  local compose_image=""
  compose_image="$(
    docker compose config 2>/dev/null | awk '
      $1 == "openclaw-gateway:" {
        in_service = 1
        next
      }
      in_service && /^[^[:space:]]/ {
        in_service = 0
      }
      in_service && $1 == "image:" {
        print $2
        exit
      }
    '
  )"

  if [[ -n "$compose_image" ]]; then
    printf '%s\n' "$compose_image"
    return 0
  fi

  printf '%s\n' "openclaw:local"
}

ensure_gateway_image_available() {
  local image_ref="$1"

  if docker image inspect "$image_ref" >/dev/null 2>&1; then
    return 0
  fi

  if [[ "$image_ref" == "openclaw:local" ]]; then
    printf '%s\n' "No local $image_ref image found; building it from Dockerfile..." >&2
    docker build -t "$image_ref" -f Dockerfile .
  else
    printf '%s\n' "Image $image_ref is not available locally; pulling it now..." >&2
    docker pull "$image_ref"
  fi

  docker image inspect "$image_ref" >/dev/null 2>&1 || fail "Could not resolve a local openclaw-gateway image."
}

write_override() {
  if [[ -f "$OVERRIDE_PATH" ]]; then
    if ! grep -Fq "$GENERATED_MARKER" "$OVERRIDE_PATH" && \
      ! grep -Fq "$LEGACY_GENERATED_MARKER" "$OVERRIDE_PATH"; then
      fail "Refusing to overwrite existing docker-compose.override.yml at $OVERRIDE_PATH because it was not generated by this tool."
    fi
  fi

  cat >"$OVERRIDE_PATH" <<EOF
$GENERATED_MARKER
services:
  openclaw-gateway:
    volumes:
      - ./tools/openclaw-control-ui-echarts/generated/control-ui:/app/dist/control-ui:ro
      - \${OPENCLAW_WORKSPACE_DIR}:/app/dist/control-ui/workspace-downloads:ro
      - ./docs/reference/templates:/app/docs/reference/templates:ro
EOF

  local mount=""
  for mount in "$@"; do
    printf '      - %s\n' "$mount" >>"$OVERRIDE_PATH"
  done

  cat >>"$OVERRIDE_PATH" <<'EOF'
  openclaw-tenant-platform:
    image: ${OPENCLAW_IMAGE:-openclaw:local}
    environment:
      HOME: /home/node
      OPENCLAW_CONFIG_DIR: /home/node/.openclaw
      OPENCLAW_TENANT_PLATFORM_BIND: 0.0.0.0
      OPENCLAW_TENANT_PLATFORM_PORT: 18801
      OPENCLAW_TENANT_PLATFORM_API_BASE: /tenant-platform-api/v1
      TZ: ${OPENCLAW_TZ:-UTC}
    volumes:
      - ${OPENCLAW_CONFIG_DIR}:/home/node/.openclaw
      - ./tools/openclaw-control-ui-echarts/sidecar:/app/tools/openclaw-control-ui-echarts/sidecar:ro
    command:
      [
        "node",
        "tools/openclaw-control-ui-echarts/sidecar/tenant-platform/server.mjs"
      ]
    ports:
      - "${OPENCLAW_TENANT_PLATFORM_PORT:-18801}:18801"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://127.0.0.1:18801/healthz').then((response) => process.exit(response.ok ? 0 : 1)).catch(() => process.exit(1))"
        ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
EOF

  if [[ "$#" -gt 0 ]]; then
    cat >>"$OVERRIDE_PATH" <<'EOF'
  openclaw-cli:
    volumes:
EOF

    for mount in "$@"; do
      printf '      - %s\n' "$mount" >>"$OVERRIDE_PATH"
    done
  fi
}

inject_runtime_script() {
  local index_path="$1"
  local temp_index="$index_path.tmp"

  grep -Fq 'openclaw-echarts-renderer.js' "$index_path" && return 0

  awk '
    $0 == "  </body>" {
      print "    <script type=\"module\" src=\"./assets/openclaw-echarts-renderer.js\"></script>"
    }
    { print }
  ' "$index_path" >"$temp_index"

  mv "$temp_index" "$index_path"
  grep -Fq 'openclaw-echarts-renderer.js' "$index_path" || fail "Failed to inject the ECharts runtime into $index_path"
}

replace_brand_favicons() {
  local index_path="$1"
  local python_bin
  python_bin="$(resolve_python)"

  "$python_bin" - "$index_path" <<'PY'
import pathlib
import re
import sys
import urllib.parse

index_path = pathlib.Path(sys.argv[1])
svg = """
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <defs>
    <linearGradient id="sptc-bg" x1="8" y1="6" x2="56" y2="58" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#f7fbff" />
      <stop offset="1" stop-color="#d9e6f4" />
    </linearGradient>
    <linearGradient id="sptc-stroke" x1="14" y1="10" x2="52" y2="54" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#88acd0" />
      <stop offset="1" stop-color="#5f88b1" />
    </linearGradient>
  </defs>
  <rect x="5.5" y="5.5" width="53" height="53" rx="16" fill="url(#sptc-bg)" stroke="url(#sptc-stroke)" stroke-width="1.5" />
  <text x="32" y="37" text-anchor="middle" font-size="18" font-weight="800" letter-spacing="2.2" fill="#48698d" font-family="Inter, Segoe UI, Arial, sans-serif">SPTC</text>
</svg>
""".strip()
href = "data:image/svg+xml;charset=utf-8," + urllib.parse.quote(svg)
lines = index_path.read_text(encoding="utf-8").splitlines()
filtered = [
    line
    for line in lines
    if not re.search(r'<link\\s+rel="icon"', line, flags=re.I)
    and not re.search(r'<link\\s+rel="shortcut icon"', line, flags=re.I)
    and not re.search(r'<link\\s+rel="apple-touch-icon"', line, flags=re.I)
]
try:
    head_close_index = next(index for index, line in enumerate(filtered) if "</head>" in line)
except StopIteration as exc:
    raise SystemExit(f"index.html is missing </head>: {index_path}") from exc
filtered[head_close_index:head_close_index] = [
    f'    <link rel="icon" type="image/svg+xml" href="{href}" />',
    f'    <link rel="shortcut icon" type="image/svg+xml" href="{href}" />',
    f'    <link rel="apple-touch-icon" type="image/svg+xml" href="{href}" />',
]
index_path.write_text("\n".join(filtered) + "\n", encoding="utf-8")
PY
}

inject_auto_gateway_token_bootstrap() {
  local index_path="$1"
  local token="$2"
  local python_bin

  token="$(trim_whitespace "$token")"
  [[ -n "$token" ]] || return 0

  python_bin="$(resolve_python)"

  "$python_bin" - "$index_path" "$token" <<'PY'
import json
import pathlib
import sys

index_path = pathlib.Path(sys.argv[1])
token = (sys.argv[2] or "").strip()
if not token:
    raise SystemExit(0)

html = index_path.read_text(encoding="utf-8")
if "data-openclaw-auto-token-bootstrap" in html:
    raise SystemExit(0)

token_literal = (
    json.dumps(token)
    .replace("<", "\\u003c")
    .replace(">", "\\u003e")
    .replace("&", "\\u0026")
    .replace("\u2028", "\\u2028")
    .replace("\u2029", "\\u2029")
)
script = f"""    <script data-openclaw-auto-token-bootstrap>
      ((rawToken) => {{
        const CONTROL_UI_TAB_PATHS = new Set([
          "/agents",
          "/overview",
          "/channels",
          "/instances",
          "/sessions",
          "/usage",
          "/cron",
          "/skills",
          "/nodes",
          "/chat",
          "/config",
          "/communications",
          "/appearance",
          "/automation",
          "/infrastructure",
          "/ai-agents",
          "/debug",
          "/logs",
        ]);
        const normalizeBasePath = (basePath) => {{
          if (!basePath) return "";
          let base = String(basePath).trim();
          if (!base) return "";
          if (!base.startsWith("/")) base = `/${{base}}`;
          if (base === "/") return "";
          if (base.endsWith("/")) base = base.slice(0, -1);
          return base;
        }};
        const normalizePath = (value) => {{
          if (!value) return "/";
          let normalized = String(value).trim();
          if (!normalized.startsWith("/")) normalized = `/${{normalized}}`;
          if (normalized.length > 1 && normalized.endsWith("/")) {{
            normalized = normalized.slice(0, -1);
          }}
          return normalized;
        }};
        const inferBasePathFromPathname = (pathname) => {{
          let normalized = normalizePath(pathname);
          if (normalized.endsWith("/index.html")) {{
            normalized = normalizePath(normalized.slice(0, -"/index.html".length));
          }}
          if (normalized === "/") return "";
          const segments = normalized.split("/").filter(Boolean);
          if (segments.length === 0) return "";
          for (let index = 0; index < segments.length; index += 1) {{
            const candidate = `/${{segments.slice(index).join("/")}}`.toLowerCase();
            if (CONTROL_UI_TAB_PATHS.has(candidate)) {{
              const prefix = segments.slice(0, index);
              return prefix.length > 0 ? `/${{prefix.join("/")}}` : "";
            }}
          }}
          return `/${{segments.join("/")}}`;
        }};
        const normalizeGatewayTokenScope = (gatewayUrl) => {{
          const trimmed = String(gatewayUrl || "").trim();
          if (!trimmed) return "default";
          try {{
            const base =
              typeof location !== "undefined"
                ? `${{location.protocol}}//${{location.host}}${{location.pathname || "/"}}`
                : undefined;
            const parsed = base ? new URL(trimmed, base) : new URL(trimmed);
            const pathname =
              parsed.pathname === "/"
                ? ""
                : parsed.pathname.replace(/\\/+$/, "") || parsed.pathname;
            return `${{parsed.protocol}}//${{parsed.host}}${{pathname}}`;
          }} catch {{
            return trimmed;
          }}
        }};
        const token = String(rawToken ?? "").trim();
        if (!token || typeof window === "undefined" || typeof location === "undefined") {{
          return;
        }}
        try {{
          const storage = window.sessionStorage;
          if (!storage) return;
          const configured =
            typeof window.__OPENCLAW_CONTROL_UI_BASE_PATH__ === "string" &&
            window.__OPENCLAW_CONTROL_UI_BASE_PATH__.trim();
          const basePath = configured
            ? normalizeBasePath(window.__OPENCLAW_CONTROL_UI_BASE_PATH__)
            : inferBasePathFromPathname(location.pathname);
          const proto = location.protocol === "https:" ? "wss" : "ws";
          const gatewayUrl = `${{proto}}://${{location.host}}${{basePath}}`;
          const scope = normalizeGatewayTokenScope(gatewayUrl);
          storage.setItem(`openclaw.control.token.v1:${{scope}}`, token);
          window.__OPENCLAW_CONTROL_UI_AUTO_TOKEN__ = true;
        }} catch {{
          // best-effort only
        }}
      }})({token_literal});
    </script>
"""

if "</head>" not in html:
    raise SystemExit(f"index.html is missing </head>: {index_path}")

html = html.replace("  </head>", f"{script}\n  </head>", 1)
index_path.write_text(html, encoding="utf-8")
PY
}

extract_offline_vendors() {
  local bundle_path="$1"
  local vendor_dir="$2"
  local python_bin

  python_bin="$(resolve_python)"
  mkdir -p "$vendor_dir"

  "$python_bin" - "$bundle_path" "$vendor_dir" <<'PY'
import json
import pathlib
import re
import sys

bundle_path = pathlib.Path(sys.argv[1])
vendor_dir = pathlib.Path(sys.argv[2])
bundle_source = bundle_path.read_text(encoding="utf-8")
match = re.search(
    r'const EMBEDDED_LIBRARY_SOURCES = \{\s*echarts:\s*("(?:\\.|[^"\\])*")\s*,\s*json5:\s*("(?:\\.|[^"\\])*")\s*,\s*\};',
    bundle_source,
    re.S,
)
if not match:
    raise SystemExit(
        f"ERROR: Could not extract embedded vendor sources from {bundle_path}"
    )

(vendor_dir / "echarts.min.js").write_text(json.loads(match.group(1)), encoding="utf-8")
(vendor_dir / "json5.min.js").write_text(json.loads(match.group(2)), encoding="utf-8")
PY

  [[ -f "$vendor_dir/echarts.min.js" ]] || fail "Failed to write $vendor_dir/echarts.min.js"
  [[ -f "$vendor_dir/json5.min.js" ]] || fail "Failed to write $vendor_dir/json5.min.js"
}

resolve_source_dir() {
  if [[ -f "$ROOT_DIR/dist/control-ui/index.html" ]]; then
    printf '%s\n' "$ROOT_DIR/dist/control-ui"
    return 0
  fi

  command -v docker >/dev/null 2>&1 || fail "docker is required when dist/control-ui is not present on the host."

  printf '%s\n' "Host dist/control-ui is missing; extracting it from the Docker image..." >&2

  local image_ref
  image_ref="$(resolve_gateway_image_ref)"
  ensure_gateway_image_available "$image_ref"

  local extracted_dir="$tmp_dir/source-control-ui"
  mkdir -p "$extracted_dir"

  container_id="$(docker create "$image_ref")"
  docker cp "$container_id:/app/dist/control-ui/." "$extracted_dir"
  docker rm -f "$container_id" >/dev/null 2>&1 || true
  container_id=""

  [[ -f "$extracted_dir/index.html" ]] || fail "The Docker image does not contain /app/dist/control-ui/index.html"
  printf '%s\n' "$extracted_dir"
}

main() {
  require_file "$CONTROL_UI_RUNTIME_SCRIPT" "Control UI ECharts runtime"
  require_dir "$CONTROL_UI_RUNTIME_MODULE_DIR" "Control UI ECharts runtime modules"
  require_dir "$CONTROL_UI_STATIC_DIR" "Control UI static overlay assets"
  require_file "$OFFLINE_BUNDLED_USERSCRIPT" "Offline bundled ECharts userscript"

  local source_dir
  source_dir="$(resolve_source_dir)"

  rm -rf "$OUTPUT_DIR"
  mkdir -p "$OUTPUT_DIR/assets/vendor"
  cp -R "$source_dir"/. "$OUTPUT_DIR"/
  cp -R "$CONTROL_UI_STATIC_DIR"/. "$OUTPUT_DIR"/
  mkdir -p "$OUTPUT_DIR/workspace-downloads"

  cp "$CONTROL_UI_RUNTIME_SCRIPT" "$OUTPUT_DIR/assets/openclaw-echarts-renderer.js"
  cp -R "$CONTROL_UI_RUNTIME_MODULE_DIR" "$OUTPUT_DIR/assets/runtime"
  extract_offline_vendors "$OFFLINE_BUNDLED_USERSCRIPT" "$OUTPUT_DIR/assets/vendor"

  [[ -f "$OUTPUT_DIR/index.html" ]] || fail "Generated Control UI root is missing index.html"
  local auto_gateway_token
  auto_gateway_token="$(resolve_auto_gateway_token)"
  inject_lufeng_public_bootstrap "$OUTPUT_DIR/index.html" "$auto_gateway_token"
  inject_auto_gateway_token_bootstrap "$OUTPUT_DIR/index.html" "$auto_gateway_token"
  inject_runtime_script "$OUTPUT_DIR/index.html"
  replace_brand_favicons "$OUTPUT_DIR/index.html"
  collect_extra_mounts
  write_override "${COLLECTED_EXTRA_MOUNTS[@]}"

  printf '%s\n' "Custom Control UI root written to: $OUTPUT_DIR"
  printf '%s\n' "Wrote $OVERRIDE_PATH"
  if [[ "${#COLLECTED_EXTRA_MOUNTS[@]}" -gt 0 ]]; then
    printf '%s\n' "Included ${#COLLECTED_EXTRA_MOUNTS[@]} extra bind mount(s) from OPENCLAW_EXTRA_MOUNTS."
  fi
  printf '%s\n' 'You can now run `docker compose up -d` from the repo root and the custom Control UI will be mounted automatically.'
}

main "$@"
