#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TOOL_DIR="$ROOT_DIR/tools/openclaw-control-ui-echarts"
OUTPUT_DIR="$TOOL_DIR/generated/control-ui"
CONTROL_UI_RUNTIME_SCRIPT="$TOOL_DIR/openclaw-echarts-renderer.js"
CONTROL_UI_RUNTIME_MODULE_DIR="$TOOL_DIR/runtime"
CONTROL_UI_STATIC_DIR="$TOOL_DIR/static"
OFFLINE_BUNDLED_USERSCRIPT="$ROOT_DIR/tools/openclaw-echarts-userscript/openclaw-echarts-renderer.user.js"
OVERRIDE_PATH="$ROOT_DIR/docker-compose.override.yml"
ENV_FILE="$ROOT_DIR/.env"

GENERATED_MARKER="# Generated by tools/openclaw-control-ui-echarts setup tool"
LEGACY_GENERATED_MARKER="# Generated by tools/openclaw-control-ui-echarts/setup-direct-docker-compose-up.mjs"

tmp_dir="$(mktemp -d)"
container_id=""

cleanup() {
  if [[ -n "$container_id" ]]; then
    docker rm -f "$container_id" >/dev/null 2>&1 || true
  fi
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

COLLECTED_EXTRA_MOUNTS=()

fail() {
  printf '%s\n' "ERROR: $*" >&2
  exit 1
}

require_file() {
  local file_path="$1"
  local label="$2"
  [[ -f "$file_path" ]] || fail "$label not found at $file_path"
}

require_dir() {
  local dir_path="$1"
  local label="$2"
  [[ -d "$dir_path" ]] || fail "$label not found at $dir_path"
}

reset_output_dir_preserve_mount() {
  local dir_path="$1"
  mkdir -p "$dir_path"
  find "$dir_path" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
}

trim_whitespace() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s\n' "$value"
}

read_dotenv_value() {
  local key="$1"
  [[ -f "$ENV_FILE" ]] || return 0

  awk -F= -v key="$key" '
    index($0, key "=") == 1 {
      sub(/^[^=]*=/, "")
      sub(/\r$/, "")
      print
      exit
    }
  ' "$ENV_FILE"
}

resolve_auto_gateway_token() {
  local token="${OPENCLAW_GATEWAY_TOKEN:-}"
  if [[ -z "$token" ]]; then
    token="$(read_dotenv_value OPENCLAW_GATEWAY_TOKEN || true)"
  fi
  trim_whitespace "$token"
}

inject_lufeng_public_bootstrap() {
  local index_path="$1"
  local token="$2"
  local python_bin

  python_bin="$(resolve_python)"

  "$python_bin" - "$index_path" "$token" <<'PY'
import pathlib
import sys

index_path = pathlib.Path(sys.argv[1])
token = (sys.argv[2] or "").strip()

html = index_path.read_text(encoding="utf-8")
if "data-openclaw-lufeng-bootstrap" in html:
    raise SystemExit(0)

token_attr = (
    token.replace("&", "&amp;")
    .replace('"', "&quot;")
    .replace("<", "&lt;")
    .replace(">", "&gt;")
)
script = (
    '    <script src="./assets/runtime/lufeng/preboot.js" '
    f'data-openclaw-lufeng-bootstrap data-gateway-token="{token_attr}"></script>'
)

if "</head>" not in html:
    raise SystemExit(f"index.html is missing </head>: {index_path}")

html = html.replace("  </head>", f"{script}\n  </head>", 1)
index_path.write_text(html, encoding="utf-8")
PY
}

validate_extra_mount_spec() {
  local mount="$1"

  [[ "$mount" == *$'\n'* || "$mount" == *$'\r'* || "$mount" == *$'\t'* ]] && \
    fail "OPENCLAW_EXTRA_MOUNTS entries cannot contain control characters."

  [[ "$mount" =~ [[:space:]] ]] && \
    fail "OPENCLAW_EXTRA_MOUNTS entries must not contain spaces."

  [[ "$mount" == *:* ]] || fail "Invalid OPENCLAW_EXTRA_MOUNTS entry: $mount"
}

collect_extra_mounts() {
  local raw_mounts="${OPENCLAW_EXTRA_MOUNTS:-}"
  local mount=""

  COLLECTED_EXTRA_MOUNTS=()

  if [[ -z "$raw_mounts" ]]; then
    raw_mounts="$(read_dotenv_value OPENCLAW_EXTRA_MOUNTS || true)"
  fi

  raw_mounts="$(trim_whitespace "$raw_mounts")"
  [[ -n "$raw_mounts" ]] || return 0

  [[ "$raw_mounts" == *$'\n'* || "$raw_mounts" == *$'\r'* || "$raw_mounts" == *$'\t'* ]] && \
    fail "OPENCLAW_EXTRA_MOUNTS cannot contain control characters."

  IFS=',' read -r -a mounts <<<"$raw_mounts"
  for mount in "${mounts[@]}"; do
    mount="$(trim_whitespace "$mount")"
    [[ -n "$mount" ]] || continue
    validate_extra_mount_spec "$mount"
    COLLECTED_EXTRA_MOUNTS+=("$mount")
  done
}

resolve_python() {
  if command -v python3 >/dev/null 2>&1; then
    printf '%s\n' "python3"
    return 0
  fi

  if command -v python >/dev/null 2>&1; then
    printf '%s\n' "python"
    return 0
  fi

  fail "python3 or python is required to extract the bundled vendor libraries."
}

resolve_gateway_image_ref() {
  if [[ -n "${OPENCLAW_IMAGE:-}" ]]; then
    printf '%s\n' "$OPENCLAW_IMAGE"
    return 0
  fi

  local compose_image=""
  compose_image="$(
    docker compose config 2>/dev/null | awk '
      $1 == "openclaw-gateway:" {
        in_service = 1
        next
      }
      in_service && /^[^[:space:]]/ {
        in_service = 0
      }
      in_service && $1 == "image:" {
        print $2
        exit
      }
    '
  )"

  if [[ -n "$compose_image" ]]; then
    printf '%s\n' "$compose_image"
    return 0
  fi

  printf '%s\n' "openclaw:local"
}

ensure_gateway_image_available() {
  local image_ref="$1"

  if docker image inspect "$image_ref" >/dev/null 2>&1; then
    return 0
  fi

  if [[ "$image_ref" == "openclaw:local" ]]; then
    printf '%s\n' "No local $image_ref image found; building it from Dockerfile..." >&2
    docker build -t "$image_ref" -f Dockerfile .
  else
    printf '%s\n' "Image $image_ref is not available locally; pulling it now..." >&2
    docker pull "$image_ref"
  fi

  docker image inspect "$image_ref" >/dev/null 2>&1 || fail "Could not resolve a local openclaw-gateway image."
}

write_override() {
  if [[ -f "$OVERRIDE_PATH" ]]; then
    if ! grep -Fq "$GENERATED_MARKER" "$OVERRIDE_PATH" && \
      ! grep -Fq "$LEGACY_GENERATED_MARKER" "$OVERRIDE_PATH"; then
      fail "Refusing to overwrite existing docker-compose.override.yml at $OVERRIDE_PATH because it was not generated by this tool."
    fi
  fi

  cat >"$OVERRIDE_PATH" <<EOF
$GENERATED_MARKER
services:
  openclaw-gateway:
    volumes:
      - ./tools/openclaw-control-ui-echarts/generated/control-ui:/app/dist/control-ui:ro
      - \${OPENCLAW_WORKSPACE_DIR}:/app/dist/control-ui/workspace-downloads:ro
      - \${OPENCLAW_CONFIG_DIR}/workspace-agents:/app/dist/control-ui/workspace-agent-downloads:ro
      - ./docs/reference/templates:/app/docs/reference/templates:ro
EOF

  local mount=""
  for mount in "$@"; do
    printf '      - %s\n' "$mount" >>"$OVERRIDE_PATH"
  done

  cat >>"$OVERRIDE_PATH" <<'EOF'
  openclaw-tenant-platform:
    image: ${OPENCLAW_IMAGE:-openclaw:local}
    environment:
      HOME: /home/node
      OPENCLAW_CONFIG_DIR: /home/node/.openclaw
      OPENCLAW_TENANT_PLATFORM_BIND: 0.0.0.0
      OPENCLAW_TENANT_PLATFORM_PORT: 18801
      OPENCLAW_TENANT_PLATFORM_API_BASE: /tenant-platform-api/v1
      OPENCLAW_TENANT_PLATFORM_EDITION: ${OPENCLAW_TENANT_PLATFORM_EDITION:-cloud}
      OPENCLAW_TENANT_PLATFORM_LICENSE_PATH: ${OPENCLAW_TENANT_PLATFORM_LICENSE_PATH:-}
      OPENCLAW_TENANT_PLATFORM_LICENSE_PUBLIC_KEY: ${OPENCLAW_TENANT_PLATFORM_LICENSE_PUBLIC_KEY:-}
      OPENCLAW_TENANT_PLATFORM_LICENSE_PUBLIC_KEY_PATH: ${OPENCLAW_TENANT_PLATFORM_LICENSE_PUBLIC_KEY_PATH:-}
      TZ: ${OPENCLAW_TZ:-UTC}
    volumes:
      - ${OPENCLAW_CONFIG_DIR}:/home/node/.openclaw
      - ./tools/openclaw-control-ui-echarts/sidecar:/app/tools/openclaw-control-ui-echarts/sidecar:ro
    command:
      [
        "node",
        "tools/openclaw-control-ui-echarts/sidecar/tenant-platform/server.mjs"
      ]
    ports:
      - "${OPENCLAW_TENANT_PLATFORM_PORT:-18801}:18801"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://127.0.0.1:18801/healthz').then((response) => process.exit(response.ok ? 0 : 1)).catch(() => process.exit(1))"
        ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
EOF

  if [[ "$#" -gt 0 ]]; then
    cat >>"$OVERRIDE_PATH" <<'EOF'
  openclaw-cli:
    volumes:
EOF

    for mount in "$@"; do
      printf '      - %s\n' "$mount" >>"$OVERRIDE_PATH"
    done
  fi
}

sync_gateway_control_ui_root() {
  if ! command -v docker >/dev/null 2>&1; then
    printf '%s\n' "WARN: docker not found; skip syncing gateway.controlUi.root." >&2
    return 0
  fi
  if ! (cd "$ROOT_DIR" && docker compose config >/dev/null 2>&1); then
    printf '%s\n' "WARN: docker compose is not available in repo root; skip syncing gateway.controlUi.root." >&2
    return 0
  fi
  if cd "$ROOT_DIR" && docker compose run --rm --no-deps openclaw-cli config set gateway.controlUi.root /app/dist/control-ui >/dev/null 2>&1; then
    printf '%s\n' "Synced gateway.controlUi.root=/app/dist/control-ui"
  else
    printf '%s\n' "WARN: failed to sync gateway.controlUi.root automatically; run this manually:" >&2
    printf '%s\n' "  docker compose run --rm --no-deps openclaw-cli config set gateway.controlUi.root /app/dist/control-ui" >&2
  fi
}

inject_runtime_script() {
  local index_path="$1"
  local temp_index="$index_path.tmp"

  grep -Fq 'openclaw-echarts-renderer.js' "$index_path" && return 0

  awk '
    $0 == "  </body>" {
      print "    <script type=\"module\" src=\"./assets/openclaw-echarts-renderer.js\"></script>"
    }
    { print }
  ' "$index_path" >"$temp_index"

  mv "$temp_index" "$index_path"
  grep -Fq 'openclaw-echarts-renderer.js' "$index_path" || fail "Failed to inject the ECharts runtime into $index_path"
}

replace_brand_favicons() {
  local index_path="$1"
  local python_bin
  python_bin="$(resolve_python)"

  "$python_bin" - "$index_path" <<'PY'
import pathlib
import re
import sys
import urllib.parse

index_path = pathlib.Path(sys.argv[1])
svg = """
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <defs>
    <linearGradient id="sptc-bg" x1="8" y1="6" x2="56" y2="58" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#f7fbff" />
      <stop offset="1" stop-color="#d9e6f4" />
    </linearGradient>
    <linearGradient id="sptc-stroke" x1="14" y1="10" x2="52" y2="54" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#88acd0" />
      <stop offset="1" stop-color="#5f88b1" />
    </linearGradient>
  </defs>
  <rect x="5.5" y="5.5" width="53" height="53" rx="16" fill="url(#sptc-bg)" stroke="url(#sptc-stroke)" stroke-width="1.5" />
  <text x="32" y="37" text-anchor="middle" font-size="18" font-weight="800" letter-spacing="2.2" fill="#48698d" font-family="Inter, Segoe UI, Arial, sans-serif">SPTC</text>
</svg>
""".strip()
href = "data:image/svg+xml;charset=utf-8," + urllib.parse.quote(svg)
lines = index_path.read_text(encoding="utf-8").splitlines()
filtered = [
    line
    for line in lines
    if not re.search(r'<link\\s+rel="icon"', line, flags=re.I)
    and not re.search(r'<link\\s+rel="shortcut icon"', line, flags=re.I)
    and not re.search(r'<link\\s+rel="apple-touch-icon"', line, flags=re.I)
]
try:
    head_close_index = next(index for index, line in enumerate(filtered) if "</head>" in line)
except StopIteration as exc:
    raise SystemExit(f"index.html is missing </head>: {index_path}") from exc
filtered[head_close_index:head_close_index] = [
    f'    <link rel="icon" type="image/svg+xml" href="{href}" />',
    f'    <link rel="shortcut icon" type="image/svg+xml" href="{href}" />',
    f'    <link rel="apple-touch-icon" type="image/svg+xml" href="{href}" />',
]
index_path.write_text("\n".join(filtered) + "\n", encoding="utf-8")
PY
}

inject_auto_gateway_token_bootstrap() {
  local index_path="$1"
  local token="$2"
  local python_bin

  token="$(trim_whitespace "$token")"
  [[ -n "$token" ]] || return 0

  python_bin="$(resolve_python)"

  "$python_bin" - "$index_path" "$token" <<'PY'
import pathlib
import sys

index_path = pathlib.Path(sys.argv[1])
token = (sys.argv[2] or "").strip()
if not token:
    raise SystemExit(0)

html = index_path.read_text(encoding="utf-8")
if "data-openclaw-auto-token-bootstrap" in html:
    raise SystemExit(0)

token_attr = (
    token.replace("&", "&amp;")
    .replace('"', "&quot;")
    .replace("<", "&lt;")
    .replace(">", "&gt;")
)
script = (
    '    <script src="./assets/runtime/branding/auto-token-preboot.js" '
    f'data-openclaw-auto-token-bootstrap data-gateway-token="{token_attr}"></script>'
)

if "</head>" not in html:
    raise SystemExit(f"index.html is missing </head>: {index_path}")

html = html.replace("  </head>", f"{script}\n  </head>", 1)
index_path.write_text(html, encoding="utf-8")
PY
}

create_login_route_entry() {
  local index_path="$1"
  local login_dir
  local login_html
  local temp_login
  login_dir="$(dirname "$index_path")/login"
  login_html="$(dirname "$index_path")/login.html"
  temp_login="$(mktemp)"
  mkdir -p "$login_dir"

  if grep -Eqi '<base[[:space:]][^>]*href=' "$index_path"; then
    cp "$index_path" "$login_dir/index.html"
    cp "$index_path" "$login_html"
    return 0
  fi

  awk '
    BEGIN { inserted = 0 }
    /<\/head>/ && inserted == 0 {
      print "    <base href=\"/\" />"
      inserted = 1
    }
    { print }
  ' "$index_path" >"$temp_login"

  cp "$temp_login" "$login_dir/index.html"
  cp "$temp_login" "$login_html"
  rm -f "$temp_login"
}

extract_offline_vendors() {
  local bundle_path="$1"
  local vendor_dir="$2"
  local python_bin

  python_bin="$(resolve_python)"
  mkdir -p "$vendor_dir"

  "$python_bin" - "$bundle_path" "$vendor_dir" <<'PY'
import json
import pathlib
import re
import sys

bundle_path = pathlib.Path(sys.argv[1])
vendor_dir = pathlib.Path(sys.argv[2])
bundle_source = bundle_path.read_text(encoding="utf-8")
match = re.search(
    r'const EMBEDDED_LIBRARY_SOURCES = \{\s*echarts:\s*("(?:\\.|[^"\\])*")\s*,\s*json5:\s*("(?:\\.|[^"\\])*")\s*,\s*\};',
    bundle_source,
    re.S,
)
if not match:
    raise SystemExit(
        f"ERROR: Could not extract embedded vendor sources from {bundle_path}"
    )

(vendor_dir / "echarts.min.js").write_text(json.loads(match.group(1)), encoding="utf-8")
(vendor_dir / "json5.min.js").write_text(json.loads(match.group(2)), encoding="utf-8")
PY

  [[ -f "$vendor_dir/echarts.min.js" ]] || fail "Failed to write $vendor_dir/echarts.min.js"
  [[ -f "$vendor_dir/json5.min.js" ]] || fail "Failed to write $vendor_dir/json5.min.js"
}

resolve_source_dir() {
  if [[ -f "$ROOT_DIR/dist/control-ui/index.html" ]]; then
    printf '%s\n' "$ROOT_DIR/dist/control-ui"
    return 0
  fi

  command -v docker >/dev/null 2>&1 || fail "docker is required when dist/control-ui is not present on the host."

  printf '%s\n' "Host dist/control-ui is missing; extracting it from the Docker image..." >&2

  local image_ref
  image_ref="$(resolve_gateway_image_ref)"
  ensure_gateway_image_available "$image_ref"

  local extracted_dir="$tmp_dir/source-control-ui"
  mkdir -p "$extracted_dir"

  container_id="$(docker create "$image_ref")"
  docker cp "$container_id:/app/dist/control-ui/." "$extracted_dir"
  docker rm -f "$container_id" >/dev/null 2>&1 || true
  container_id=""

  [[ -f "$extracted_dir/index.html" ]] || fail "The Docker image does not contain /app/dist/control-ui/index.html"
  printf '%s\n' "$extracted_dir"
}

main() {
  require_file "$CONTROL_UI_RUNTIME_SCRIPT" "Control UI ECharts runtime"
  require_dir "$CONTROL_UI_RUNTIME_MODULE_DIR" "Control UI ECharts runtime modules"
  require_dir "$CONTROL_UI_STATIC_DIR" "Control UI static overlay assets"
  require_file "$OFFLINE_BUNDLED_USERSCRIPT" "Offline bundled ECharts userscript"

  local source_dir
  source_dir="$(resolve_source_dir)"

  reset_output_dir_preserve_mount "$OUTPUT_DIR"
  mkdir -p "$OUTPUT_DIR/assets/vendor"
  cp -R "$source_dir"/. "$OUTPUT_DIR"/
  cp -R "$CONTROL_UI_STATIC_DIR"/. "$OUTPUT_DIR"/
  mkdir -p "$OUTPUT_DIR/workspace-downloads"
  mkdir -p "$OUTPUT_DIR/workspace-agent-downloads"

  cp "$CONTROL_UI_RUNTIME_SCRIPT" "$OUTPUT_DIR/assets/openclaw-echarts-renderer.js"
  cp -R "$CONTROL_UI_RUNTIME_MODULE_DIR" "$OUTPUT_DIR/assets/runtime"
  extract_offline_vendors "$OFFLINE_BUNDLED_USERSCRIPT" "$OUTPUT_DIR/assets/vendor"

  [[ -f "$OUTPUT_DIR/index.html" ]] || fail "Generated Control UI root is missing index.html"
  local auto_gateway_token
  auto_gateway_token="$(resolve_auto_gateway_token)"
  inject_lufeng_public_bootstrap "$OUTPUT_DIR/index.html" "$auto_gateway_token"
  inject_auto_gateway_token_bootstrap "$OUTPUT_DIR/index.html" "$auto_gateway_token"
  inject_runtime_script "$OUTPUT_DIR/index.html"
  replace_brand_favicons "$OUTPUT_DIR/index.html"
  create_login_route_entry "$OUTPUT_DIR/index.html"
  collect_extra_mounts
  write_override "${COLLECTED_EXTRA_MOUNTS[@]}"
  sync_gateway_control_ui_root

  printf '%s\n' "Custom Control UI root written to: $OUTPUT_DIR"
  printf '%s\n' "Wrote $OVERRIDE_PATH"
  if [[ "${#COLLECTED_EXTRA_MOUNTS[@]}" -gt 0 ]]; then
    printf '%s\n' "Included ${#COLLECTED_EXTRA_MOUNTS[@]} extra bind mount(s) from OPENCLAW_EXTRA_MOUNTS."
  fi
  printf '%s\n' 'You can now run `docker compose up -d` from the repo root and the custom Control UI will be mounted automatically.'
}

main "$@"
