#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TOOL_DIR="$ROOT_DIR/tools/openclaw-control-ui-echarts"
OUTPUT_DIR="$TOOL_DIR/generated/control-ui"
RUNTIME_SCRIPT="$ROOT_DIR/tools/openclaw-echarts-userscript/openclaw-echarts-renderer.user.js"
OVERRIDE_PATH="$ROOT_DIR/docker-compose.override.yml"

GENERATED_MARKER="# Generated by tools/openclaw-control-ui-echarts setup tool"
LEGACY_GENERATED_MARKER="# Generated by tools/openclaw-control-ui-echarts/setup-direct-docker-compose-up.mjs"

tmp_dir="$(mktemp -d)"
container_id=""

cleanup() {
  if [[ -n "$container_id" ]]; then
    docker rm -f "$container_id" >/dev/null 2>&1 || true
  fi
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

fail() {
  printf '%s\n' "ERROR: $*" >&2
  exit 1
}

require_file() {
  local file_path="$1"
  local label="$2"
  [[ -f "$file_path" ]] || fail "$label not found at $file_path"
}

resolve_gateway_image_ref() {
  if [[ -n "${OPENCLAW_IMAGE:-}" ]]; then
    printf '%s\n' "$OPENCLAW_IMAGE"
    return 0
  fi

  local compose_image=""
  compose_image="$(
    docker compose config 2>/dev/null | awk '
      $1 == "openclaw-gateway:" {
        in_service = 1
        next
      }
      in_service && /^[^[:space:]]/ {
        in_service = 0
      }
      in_service && $1 == "image:" {
        print $2
        exit
      }
    '
  )"

  if [[ -n "$compose_image" ]]; then
    printf '%s\n' "$compose_image"
    return 0
  fi

  printf '%s\n' "openclaw:local"
}

ensure_gateway_image_available() {
  local image_ref="$1"

  if docker image inspect "$image_ref" >/dev/null 2>&1; then
    return 0
  fi

  if [[ "$image_ref" == "openclaw:local" ]]; then
    printf '%s\n' "No local $image_ref image found; building it from Dockerfile..." >&2
    docker build -t "$image_ref" -f Dockerfile .
  else
    printf '%s\n' "Image $image_ref is not available locally; pulling it now..." >&2
    docker pull "$image_ref"
  fi

  docker image inspect "$image_ref" >/dev/null 2>&1 || fail "Could not resolve a local openclaw-gateway image."
}

write_override() {
  if [[ -f "$OVERRIDE_PATH" ]]; then
    if ! grep -Fq "$GENERATED_MARKER" "$OVERRIDE_PATH" && \
      ! grep -Fq "$LEGACY_GENERATED_MARKER" "$OVERRIDE_PATH"; then
      fail "Refusing to overwrite existing docker-compose.override.yml at $OVERRIDE_PATH because it was not generated by this tool."
    fi
  fi

  cat >"$OVERRIDE_PATH" <<EOF
$GENERATED_MARKER
services:
  openclaw-gateway:
    volumes:
      - ./tools/openclaw-control-ui-echarts/generated/control-ui:/app/dist/control-ui:ro
EOF
}

inject_runtime_script() {
  local index_path="$1"
  local temp_index="$index_path.tmp"

  grep -Fq 'openclaw-echarts-renderer.js' "$index_path" && return 0

  awk '
    $0 == "  </body>" {
      print "    <script defer src=\"./assets/openclaw-echarts-renderer.js\"></script>"
    }
    { print }
  ' "$index_path" >"$temp_index"

  mv "$temp_index" "$index_path"
  grep -Fq 'openclaw-echarts-renderer.js' "$index_path" || fail "Failed to inject the ECharts runtime into $index_path"
}

resolve_source_dir() {
  if [[ -f "$ROOT_DIR/dist/control-ui/index.html" ]]; then
    printf '%s\n' "$ROOT_DIR/dist/control-ui"
    return 0
  fi

  command -v docker >/dev/null 2>&1 || fail "docker is required when dist/control-ui is not present on the host."

  printf '%s\n' "Host dist/control-ui is missing; extracting it from the Docker image..." >&2

  local image_ref
  image_ref="$(resolve_gateway_image_ref)"
  ensure_gateway_image_available "$image_ref"

  local extracted_dir="$tmp_dir/source-control-ui"
  mkdir -p "$extracted_dir"

  container_id="$(docker create "$image_ref")"
  docker cp "$container_id:/app/dist/control-ui/." "$extracted_dir"
  docker rm -f "$container_id" >/dev/null 2>&1 || true
  container_id=""

  [[ -f "$extracted_dir/index.html" ]] || fail "The Docker image does not contain /app/dist/control-ui/index.html"
  printf '%s\n' "$extracted_dir"
}

main() {
  require_file "$RUNTIME_SCRIPT" "Bundled offline ECharts runtime"

  local source_dir
  source_dir="$(resolve_source_dir)"

  rm -rf "$OUTPUT_DIR"
  mkdir -p "$OUTPUT_DIR/assets"
  cp -R "$source_dir"/. "$OUTPUT_DIR"/

  cp "$RUNTIME_SCRIPT" "$OUTPUT_DIR/assets/openclaw-echarts-renderer.js"

  [[ -f "$OUTPUT_DIR/index.html" ]] || fail "Generated Control UI root is missing index.html"
  inject_runtime_script "$OUTPUT_DIR/index.html"
  write_override

  printf '%s\n' "Custom Control UI root written to: $OUTPUT_DIR"
  printf '%s\n' "Wrote $OVERRIDE_PATH"
  printf '%s\n' 'You can now run `docker compose up -d` from the repo root and the custom Control UI will be mounted automatically.'
}

main "$@"
